version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit_back:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - 9292:${FRONTEND_PORT}/tcp
    networks:
      - reddit_front
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      reddit_front:
      reddit_back:
        aliases:
          - post

  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      reddit_front:
      reddit_back:
        aliases: 
          - comment

volumes:
  post_db:

networks:
  reddit_front:
  reddit_back:
