version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.6.1
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.6.1
    ports:
      - "5601:5601"

