{
 "title": "UI_Sevice_Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Avg Request Count",
   "type": "graph",
   "description": "Среднее количество запросов в минуту",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{path!=\"/metrics\"}[1m])"
    }
   ]
  },
  {
   "title": "Response time 95%",
   "type": "graph",
   "description": "95 процентиль времени ответа",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Avg Request Errors",
   "type": "graph",
   "description": "В среднем за минуту ошибочных запросов",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status =~ \"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{path!=\"/metrics\"}[1m])"
    }
   ]
  }
 ]
}