kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: xkNUnsbw8IYUbdMleSSYMPjwVDJxYJwfBAu9hy9/eXs=
      - identity: {}
